FakturaMvc/FakturaMvc/Models/Faktura.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FakturaMvc.Models
{
    public class Faktura
    {
        public int idFaktura { get; set; } = 0;
        public string dostawca { get; set; } = string.Empty;
        public string odbiorca { get; set; } = string.Empty;
        public DateTime dataPlatnosci { get; set; } = DateTime.MinValue;
        public long numerNip { get; set; } = 0;
        public List<FakturaPozycja> pozycje { get; set; } = new List<FakturaPozycja>();

        public string pobierzOpis()
        {
            var opisFaktury = "╔══════════════════════════════════════════════════════════════════════════════╗\n";


            opisFaktury += "║" + String.Format("{0,-21}", " ID") + "= " + String.Format("{0,-55}", idFaktura) + "║\n";
            opisFaktury += "║" + String.Format("{0,-21}", " Dostawca") + "= " + String.Format("{0,-55}", dostawca) + "║\n";
            opisFaktury += "║" + String.Format("{0,-21}", " Odbiorca") + "= " + String.Format("{0,-55}", odbiorca) + "║\n";
            opisFaktury += "║" + String.Format("{0,-21}", " NIP") + "= " + String.Format("{0,-55}", numerNip) + "║\n";
            opisFaktury += "║" + String.Format("{0,-21}", " Data płatności") + "= " + String.Format("{0,-55}", dataPlatnosci) + "║\n";
            opisFaktury += "╠══════════════════════════════════════════════════════════════════════════════╣\n";
            opisFaktury += "║" + String.Format("{0,-78}", "Pozycja Faktury:") + "║\n";
            opisFaktury += "╠══════╦══════════════════╦═════════════╦════════════╦═══════════╦═════════════╣\n";
            opisFaktury += "║" + String.Format("{0,-5} {1,-18} {2,-10} {3,-10} {4,-10} {5,-10}", "Lp.", "║ Nazwa", "║ Kwota Netto", "║ Stawka VAT", "║ Kwota VAT", "║ Kwota Brutto") + "║\n";
            opisFaktury += "╠══════╬══════════════════╬═════════════╬════════════╬═══════════╬═════════════╣\n";
            opisFaktury += pozycja();
            // opisFaktury += "╠══════╬══════════════════╬═════════════╬════════════╬═══════════╬═════════════╣\n";
            opisFaktury += podsumowanie();
            opisFaktury += "╚══════╩══════════════════╩═════════════╩════════════╩═══════════╩═════════════╝\n";
            return opisFaktury;


        }
        public string pozycja()
        {
            var opisPozycji = "";
            foreach (var pozycjaFaktury in pozycje)
            {
                opisPozycji += "";

                opisPozycji +=String.Format("{0,-4} {1,-15} {2,4} {3,13} {4,12} {5,11} {6,9}",
                    pozycjaFaktury.lp, pozycjaFaktury.nazwa, "║", pozycjaFaktury.kwotaNetto,
                    String.Format("{0:F2} %", pozycjaFaktury.stawkaVat), String.Format("{0:N2}", (pozycjaFaktury.kwotaNetto * pozycjaFaktury.stawkaVat / 100)),
                    String.Format("{0:N2}", (pozycjaFaktury.kwotaNetto + (pozycjaFaktury.kwotaNetto * pozycjaFaktury.stawkaVat / 100))));


            }
            return opisPozycji;
        }

       
        
        public string podsumowanie()
        {
            var pods = "";
            pods += "";

            pods += "║ " + String.Format("{0,-4} {1,-15} {2,4} {3,13} {4,12} {5,11} {6,9}",
                "", "║ " + "RAZEM", "║", kwotaNetto() + " zł" + " ║", "" + " ║", String.Format("{0:N2}", kwotaVat()) + " zł" + " ║", String.Format("{0:N2}", kwotaBrutto())) + " zł" + "║\n";

            return pods;
        }

        public decimal kwotaNetto()
        {
            decimal suma = 0;
            foreach (var pozycjaFaktury in pozycje)
            {

                var kwotaNetto = pozycjaFaktury.kwotaNetto;
                suma += kwotaNetto;
            }
            return suma;
        }

        public decimal kwotaVat()
        {
            decimal sumaVat = 0;
            foreach (var pozycjaFaktury in pozycje)
            {

                var kwotaVat = (pozycjaFaktury.kwotaNetto * pozycjaFaktury.stawkaVat / 100);
                sumaVat += kwotaVat;
            }
            return sumaVat;
        }

        public decimal kwotaBrutto()
        {
            decimal suma = 0;
            foreach (var pozycjaFaktury in pozycje)
            {

                var kwotaBrutto = pozycjaFaktury.kwotaNetto + (pozycjaFaktury.kwotaNetto * pozycjaFaktury.stawkaVat / 100);
                suma += kwotaBrutto;
            }
            return suma;


        }
        public bool czyOpoznione()
        {
            if (dataPlatnosci.CompareTo(DateTime.Now) == -1)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        public bool obliczeniaNip()
        {
            var cyfra1 = numerNip / 1000000000;
            var cyfra2 = (numerNip / 100000000) % 10;
            var cyfra3 = (numerNip / 10000000) % 10;
            var cyfra4 = (numerNip / 1000000) % 10;
            var cyfra5 = (numerNip / 100000) % 10;
            var cyfra6 = (numerNip / 10000) % 10;
            var cyfra7 = (numerNip / 1000) % 10;
            var cyfra8 = (numerNip / 100) % 10;
            var cyfra9 = (numerNip / 10) % 10;
            var cyfra10 = numerNip % 10;

            var wynik = cyfra1 * 6 + cyfra2 * 5 + cyfra3 * 7 + cyfra4 * 2 + cyfra5 * 3 + cyfra6 * 4 + cyfra7 * 5 + cyfra8 * 6 + cyfra9 * 7;
            var wynik1 = wynik % 11;

            if (wynik1 == cyfra10)
            {
                return true;

            }
            else
            {
                return false;
            }

        }


    }
}

FakturaMvc/FakturaMvc/Controllers/FakturaController.cs
using FakturaMvc.Mapper;
using FakturaMvc.Models;
using FakturaMvc.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FakturaMvc.Controllers
{
    public class FakturaController : Controller
    {
        // GET: Faktura
        public ActionResult Faktura(int id)
        {
            var fakturaService = new FakturaService();
            var faktura = fakturaService.getById(id);



            ViewBag.messages = fakturaService.messages;
                   
            //var faktura = new Faktura();
            return View(faktura);


            //var fakturaDoWidoku = listaFaktur.FirstOrDefault(f => f.idFaktura == id);

            /* Faktura fakDoEdycji = null;

             foreach (var faktura in listaFaktur)
             {
                 if (faktura.idFaktura==id)
                 {
                     fakDoEdycji = faktura;
                 }

             }*/



        }

        public ActionResult ListaFaktur()
        {
            var fakturaService = new FakturaService();
            var listaFaktur = fakturaService.getList();
            return View(listaFaktur);
        }

        /*public ActionResult Edit(int id)
        {
            var fakturaMapper = new FakturaMapper();
            var nowaFaktura = fakturaMapper.getById(0);
            //var faktura = new Faktura();
            return View(nowaFaktura);
        }*/

        /*public ActionResult EdycjaFaktura()
        {
            var fakturaMapper = new FakturaMapper();
            var edycjaFaktura = fakturaMapper.getById();
            //var faktura = new Faktura();
            return View(edycjaFaktura);

        }*/

        /*public ActionResult NowaFaktura()
        {
            return View();
        }*/

       

        public ActionResult FakturaDoEdycji(int id)
        {
            Faktura fakturaDoEdycji;
            var fakturaService = FakturaService.getSingleton();

            if (id == 0)
            {
                fakturaDoEdycji = new Faktura();
            }
            else
            {
                fakturaDoEdycji = fakturaService.getById(id);
                
            }
            ViewBag.messages = fakturaService.messages;
            fakturaService.messages = new List<Message>();
            
            return View(fakturaDoEdycji);
        }



        [HttpPost]
        public ActionResult FakturaDoEdycji(Faktura fakturaDoEdycji)
        {
            var fakturaService = FakturaService.getSingleton();
            fakturaService.save(fakturaDoEdycji);           
            return Redirect($"/Faktura/Faktura/{fakturaDoEdycji.idFaktura}");
        }



        public ActionResult UsunFaktura(int id)
        {
            Faktura usunFaktura;
            var fakturaService = FakturaService.getSingleton();
            usunFaktura = fakturaService.getById(id);
            var wynik = fakturaService.delete(usunFaktura);

            //return Content($"Wynik usunięcia {wynik}");
            if (wynik == true)
            {
                return Redirect($"/Faktura/ListaFaktur");

            }
            else
            {
                return Content($"Problem z usunięciem faktury.");
            }
        }        
    }
}

FakturaMvc/FakturaMvc/Views/Faktura/Faktura.cshtml
@model FakturaMvc.Models.Faktura

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Faktura</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
</head>
<body>

    @foreach (var message in @ViewBag.messages)
    {        
        <div>@message.opis</div>
    }
    

    @if (@Model != null)
    {
        <h1> Faktura o numerze @Model.idFaktura </h1>
        <table style="width:50%; border: 1px solid black;">
            <tr>
                <td ><p align="left">ID</p></td>
                <td>@Model.idFaktura</td>
            </tr>
            <tr>
                <td  ><p  align="left">Dostawca</p></td>
                <td>@Model.dostawca</td>
            </tr>
            <tr>
                <td  ><p  align="left">Odbiorca</p></td>
                <td>@Model.odbiorca</td>
            </tr>
            <tr>
                <td  ><p  align="left">NIP</p></td>
                <td>@Model.numerNip</td>
            </tr>
            <tr>
                <td  ><p  align="left">Data wystawienia faktury</p></td>
                <td>@Model.dataPlatnosci</td>
            </tr>
        </table>

        <table style="width:50%; border: 1px solid black;">
            <tr>
                <th  ><p  align="left">Pozycje faktury:</p></th>
            </tr>
        </table>

    <table style="width:50%; border: 1px solid black;"  rules="groups">
        <colgroup span="1"></colgroup>
        <colgroup span="1"></colgroup>
        <colgroup span="1"></colgroup>
        <colgroup span="1"></colgroup>
        <colgroup span="1"></colgroup>
        <colgroup span="1"></colgroup>
   
        <tbody>
            <tr>
                <th width="30">Lp.</th>
                <th width="120">Nazwa</th>
                <th width="60">Kwota Netto</th>
                <th width="60">Stawka VAT</th>
                <th width="60">Kwota VAT</th>
                <th width="60">Kwota Brutto</th>
                <th width="60">Edycja</th>
            </tr>
        </tbody>
        <tbody>
            @foreach (var pozycjaFaktury in @Model.pozycje)
            {
                <tr>
                    <td>@pozycjaFaktury.lp</td>
                    <td>@pozycjaFaktury.nazwa</td>
                    <td align="right"><p></p>@pozycjaFaktury.kwotaNetto zł<p></p></td>
                    <td align="right">@pozycjaFaktury.stawkaVat %</td>
                    <td align="right">@pozycjaFaktury.kwotaVat zł</td>
                    <td align="right">@pozycjaFaktury.kwotaBrutto zł</td>                    
                    <td><a href="/FakturaPozycja/PozycjaDoEdycji/@Model.idFaktura/@pozycjaFaktury.lp">Edycja pozycji @pozycjaFaktury.lp</a></td>                   
                </tr>
            }

        </tbody>
        <tbody>
        <tr>
            <th width="30">----</th>
            <th width="120">RAZEM</th>
            <th width="60">@Model.kwotaNetto() zł</th>
            <th width="60">----</th>
            <th width="60">@Model.kwotaVat() zł</th>
            <th width="60">@Model.kwotaBrutto() zł</th>
            <th width="60">----</th>
        </tr>
        </tbody>

    </table>
    <div align="center">
        <b><a href="/FakturaPozycja/PozycjaDoEdycji/@Model.idFaktura/0">dodaj pozycję</a></b>
        
    </div>

    }
    

    <b><br><a href="/Faktura/ListaFaktur">Powrót do listy faktur</a></br></b>
</body>
</html>

FakturaMvc/FakturaMvc/Views/Faktura/FakturaDoEdycji.cshtml
@model FakturaMvc.Models.Faktura
@{
    Layout = null;
}

<!DOCTYPE html>


<head>
    <meta name="viewport" content="width=device-width" />
    <title>NowaFaktura</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
</head>
<body>
    @using (Html.BeginForm("FakturaDoEdycji", "Faktura", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        
            foreach (var message in ViewBag.messages)
            {
            <div>@message.opis</div>
            }
        
        
            if (Model != null)
            {
        <table style="width:50%; border: 1px solid black;">
            <tr>
               
                <td>@Html.HiddenFor(a => a.idFaktura)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.dostawca)</th>
                <td>@Html.TextBoxFor(a => a.dostawca)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.odbiorca)</th>
                <td>@Html.TextBoxFor(a => a.odbiorca)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.numerNip)</th>
                <td>@Html.TextBoxFor(a => a.numerNip)</td>
            </tr>


        </table>


        <input type="submit" value="Zapisz" />
            
        }
    }
</body>

FakturaMvc/FakturaMvc/Views/Faktura/ListaFaktur.cshtml
@model IEnumerable<FakturaMvc.Models.Faktura>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ListaFaktur</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
</head>
<body>


    <h1> Lista faktur </h1>
    <table style="width:50%; border: 1px solid black;">
        <tr>
            <th><p>ID</p></th>
            <th><p>Dostawca</p></th>
            <th><p>Odbiorca</p></th>
            <th><p>Edycja</p></th>
            <th><p>Usuń</p></th>

        </tr>

        @foreach (var faktura in Model)
        {
            <tr>
                <td>
                    <a href="/Faktura/Faktura/@faktura.idFaktura">@faktura.idFaktura</a>
                </td>
                <td>@faktura.dostawca</td>                
                <td>@faktura.odbiorca</td>
                <td>
                    <button onclick="location.href = '/Faktura/FakturaDoEdycji/@faktura.idFaktura'">Edycja Faktury @faktura.idFaktura</button>                   
                </td>
                <td>
                    <button onclick="location.href = '/Faktura/UsunFaktura/@faktura.idFaktura'">Usuń fakturę @faktura.idFaktura</button>
                </td>
            </tr>
        }
                </table>
    

    <select onchange="self.location.href = this.value">
        @foreach (var faktura in Model)
            {
            <option VALUE="/Faktura/Faktura/@faktura.idFaktura">Faktura nr @faktura.idFaktura</option>
        }
    </select>
    <br />
   
    <button onclick="location.href = '/Faktura/FakturaDoEdycji/0'">Nowa faktura</button>


</body>

</html>