FakturaMvc/FakturaMvc/Models/FakturaPozycja.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FakturaMvc.Models
{
    public class FakturaPozycja
    {
       
            public int lp { get; set; } = 0;
            public string nazwa { get; set; } = string.Empty;
            public decimal kwotaNetto { get; set; } = 0;
            public int stawkaVat { get; set; } = 0;
        public int id_faktura { get; set; } = 0;

        public decimal kwotaVat { get
            {
                var suma = Math.Round((kwotaNetto * stawkaVat / 100),2);
                return suma;
            } }


        public decimal kwotaBrutto 
        {
            get
            {
                var suma = Math.Round(kwotaNetto + (kwotaNetto * stawkaVat / 100),2);
                return suma;
            }
        }
    }
}

FakturaMvc/FakturaMvc/Controllers/FakturaPozycjaController.cs
using FakturaMvc.Models;
using FakturaMvc.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FakturaMvc.Controllers
{
    public class FakturaPozycjaController : Controller
    {
        //GET: Faktura
        public ActionResult Pozycja (int id)
        {
            var fakturaPozycjaService = new FakturaService();
            var pozycja = fakturaPozycjaService.getPozycjaById(id);
            ViewBag.messages = fakturaPozycjaService.messages;
            return View(pozycja);
        }


        public ActionResult ListaPozycji(int id_pozycja)
        {
            var fakturaPozycjaService = new FakturaService();
            var listaPozycja = fakturaPozycjaService.getPozycjaList(id_pozycja);
            return View(listaPozycja);
        }


        public ActionResult PozycjaDoEdycji(int id, int id2)
        {
            FakturaPozycja pozycjaDoEdycji;
            var fakturaPozycjaService = FakturaService.getSingleton();

            if (id == 0)
            {
                pozycjaDoEdycji = new FakturaPozycja();
            }
            else
            {
                pozycjaDoEdycji = fakturaPozycjaService.getPozycjaById(id2);
            }

            pozycjaDoEdycji.id_faktura = id;
            ViewBag.messages = fakturaPozycjaService.messages;

            return View(pozycjaDoEdycji);
        }
        [HttpPost]
        public ActionResult PozycjaDoEdycji(FakturaPozycja pozycjaDoEdycji)
        {
            var fakturaPozycjaService = FakturaService.getSingleton();
            fakturaPozycjaService.save(pozycjaDoEdycji);
            return Redirect($"/Faktura/Faktura/{pozycjaDoEdycji.id_faktura}");
        }
        public ActionResult UsunPozycja(int lp)
        {
            FakturaPozycja usunPozycja;
            var fakturaPozycjaService = FakturaService.getSingleton();
            usunPozycja = fakturaPozycjaService.getPozycjaById(lp);
            var wynik = fakturaPozycjaService.delete(usunPozycja);

            //return Content($"Wynik usunięcia {wynik}");
            if (wynik == true)
            {
                return Content($"Pomyślnie usunięto pozycję.");

            }
            else
            {
                return Content($"Problem z usunięciem pozycji.");
            }
        }
    }
}

FakturaMvc/FakturaMvc/Views/FakturaPozycja/PozycjaDoEdycji.cshtml
@model FakturaMvc.Models.FakturaPozycja
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PozycjaFakturaDoEdycji</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
</head>
<body>
    @using (Html.BeginForm("PozycjaDoEdycji", "FakturaPozycja", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        
            foreach (var message in @ViewBag.messages)
            {

            <div>@message.opis</div>
            }
        

        
            if (@Model != null)
            {
        <table style="width:50%; border: 1px solid black;">
            <tr>
                <th>@Html.LabelFor(a => a.lp)</th>
                <td>@Html.TextBoxFor(a => a.lp)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.nazwa)</th>
                <td>@Html.TextBoxFor(a => a.nazwa)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.kwotaNetto)</th>
                <td>@Html.TextBoxFor(a => a.kwotaNetto)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.stawkaVat)</th>
                <td>@Html.TextBoxFor(a => a.stawkaVat)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.id_faktura)</th>
                <td>@Html.TextBoxFor(a => a.id_faktura, new Dictionary<string, object>() { { "readonly", "true" } })</td>
            </tr>
        </table>
        <input type="submit" value="Zapisz" />
            }
        
    }
    <a href="/Faktura/Faktura/@Model.id_faktura">Powrót do podglądu faktury</a>
</body>
</html>