FakturaMvc/FakturaMvc/Models/Ksiazka.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FakturaMvc.Models
{
    public class Ksiazka
    {
        public int id { get; set; } = 0;
        public string tytul { get; set; } = string.Empty;
        public long isbn { get; set; } = 0;
        public decimal cena { get; set; } = 0;
        public string autor { get; set; } = string.Empty;

        public string cena2()
        //string cena3;
        //cena3 = String.Format("{0:F2} zł", cena);
        //return cena3;


        {

            return String.Format("{0:F2} zł", cena);
        }


        public string pobierzOpis()
        {
            var opisKsiazki = "";
            opisKsiazki += "Tytuł: " + tytul + ", ISBN: " + isbn + ", cena: " + String.Format("{0:F2} zł", cena) + ", autor: "
                + autor;
            if (czyPoprawny() == true)
            {
                opisKsiazki = opisKsiazki + ", ISBN poprawny";
            }
            else
            {
                opisKsiazki = opisKsiazki + ", ISBN niepoprawny";
            }
            return opisKsiazki;
        }
        public bool czyPoprawny()
        {
            var cyfra1 = isbn / 1000000000000;
            var cyfra2 = (isbn / 100000000000) % 10;
            var cyfra3 = (isbn / 10000000000) % 10;
            var cyfra4 = (isbn / 1000000000) % 10;
            var cyfra5 = (isbn / 100000000) % 10;
            var cyfra6 = (isbn / 10000000) % 10;
            var cyfra7 = (isbn / 1000000) % 10;
            var cyfra8 = (isbn / 100000) % 10;
            var cyfra9 = (isbn / 10000) % 10;
            var cyfra10 = (isbn / 1000) % 10;
            var cyfra11 = (isbn / 100) % 10;
            var cyfra12 = (isbn / 10) % 10;
            var cyfra13 = isbn % 10;

            var wynik = cyfra1 * 1 + cyfra2 * 3 + cyfra3 * 1 + cyfra4 * 3 + cyfra5 * 1
                + cyfra6 * 3 + cyfra7 * 1 + cyfra8 * 3 + cyfra9 * 1 + cyfra10 * 3
                + cyfra11 * 1 + cyfra12 * 3;
            var wynik1 = wynik % 10;
            var wynik2 = wynik1 % 10;
            if (wynik2 == cyfra13)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

FakturaMvc/FakturaMvc/Controllers/KsiazkaController.cs
using FakturaMvc.Mapper;
using FakturaMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FakturaMvc.Controllers
{
    public class KsiazkaController : Controller
    {
        // GET: Ksiazka
        public ActionResult Ksiazka(int id)
        {
            var ksiazkaMapper = new KsiazkaMapper(); //dodać using ctrl+"."
            var ksiazka = ksiazkaMapper.getById(id);
            return View(ksiazka);
        }
        public ActionResult ListaKsiazek()
        {
            var ksiazkaMapper = new KsiazkaMapper();
            var listaKsiazek = ksiazkaMapper.getList();
            return View(listaKsiazek);
        }
        public ActionResult KsiazkaDoEdycji(int id)
        {
            Ksiazka ksiazkaDoEdycji;
            var ksiazkaMapper = new KsiazkaMapper();

            if (id == 0)
            {
                ksiazkaDoEdycji = new Ksiazka();
            }
            else
            {
                ksiazkaDoEdycji = ksiazkaMapper.getById(id);
            }

            return View(ksiazkaDoEdycji);
        }
        [HttpPost]
        public ActionResult KsiazkaDoEdycji(Ksiazka ksiazkaDoEdycji)
        {
            var ksiazkaMapper = new KsiazkaMapper();
            ksiazkaMapper.save(ksiazkaDoEdycji);
            return Content($"Książka nr {ksiazkaDoEdycji.id} została zapisana poprawnie");
        }
        public ActionResult UsunKsiazka(int id)
        {
            Ksiazka usunKsiazka;
            var ksiazkaMapper = new KsiazkaMapper();
            usunKsiazka = ksiazkaMapper.getById(id);
            var wynik = ksiazkaMapper.delete(usunKsiazka);

            //return Content($"Wynik usunięcia {wynik}");
            if (wynik == true)
            {
                return Content($"Pomyślnie usunięto książkę.");
            }
            else
            {
                return Content($"Problem z usunięciem książki.");
            }
        }
    }
}

FakturaMvc/FakturaMvc/Views/Ksiazka/Ksiazka.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
    <title>Ksiazka</title>
</head>
<body>
    
            <h1> Książka </h1>
            <table style="width:50%; border: 1px solid black; margin: 0 auto;">
                <tr>
                    <th align="left"><p>ID</p></th>
                    <td>@Model.id</td>
                </tr>
                <tr>
                    <th align="left"><p>Tytuł</p></th>
                    <td>@Model.tytul</td>
                </tr>
                <tr>
                    <th align="left"><p>Numer ISBN</p></th>
                    <td>@Model.isbn</td>
                </tr>
                <tr>
                    <th align="left"><p>Cena</p></th>
                    <td>@Model.cena2()</td>
                </tr>
                <tr>
                    <th align="left"><p>Autor</p></th>
                    <td>@Model.autor</td>
                </tr>
            </table>
            
</body>
</html>

FakturaMvc/FakturaMvc/Views/Ksiazka/KsiazkaDoEdycji.cshtml
@model FakturaMvc.Models.Ksiazka
@{
    Layout = null;
}

<!DOCTYPE html>


<head>
    <meta name="viewport" content="width=device-width" />
    <title>NowaKsiazka</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
</head>
<body>
    @using (Html.BeginForm("KsiazkaDoEdycji", "Ksiazka", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <table style="width:50%; border: 1px solid black;">
            <tr>
                <th>@Html.LabelFor(a => a.id)</th>
                <td>@Html.TextBoxFor(a => a.id)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.tytul)</th>
                <td>@Html.TextBoxFor(a => a.tytul)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.isbn)</th>
                <td>@Html.TextBoxFor(a => a.isbn)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.autor)</th>
                <td>@Html.TextBoxFor(a => a.autor)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.cena)</th>
                <td>@Html.TextBoxFor(a => a.cena)</td>
            </tr>

        </table>
        <input type="submit" value="Zapisz" />

    }
</body>

FakturaMvc/FakturaMvc/Views/Ksiazka/ListaKsiazek.cshtml
@model IEnumerable<FakturaMvc.Models.Ksiazka>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ListaKsiazek</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
</head>
<body>
    <h1> Książka </h1>
    <table style="width:50%; border: 1px solid black; margin: 0 auto;">
        <tr>
            <th align="left"><p>ID</p></th>
            <th align="left"><p>Tytuł</p></th>
            <th align="left"><p>Edycja</p></th>
            <th align="left"><p>Usuń</p></th>
            
        </tr>
        @foreach (var ksiazka in Model)
        {
            <tr>                
                <td><a href="/Ksiazka/Ksiazka/@ksiazka.id"><p>@ksiazka.id</p></a></td>                          
                <td><p>@ksiazka.tytul</p></td>  
                <td>
                    <button onclick="location.href = '/Ksiazka/KsiazkaDoEdycji/@ksiazka.id'">Edycja Książki @ksiazka.id</button>

                </td>
                <td>
                    <button onclick="location.href = '/Ksiazka/UsunKsiazka/@ksiazka.id'">Usuń Książkę @ksiazka.id</button>

                </td>       
            </tr>                                                
        }
    </table>    
    <select onchange="self.location.href = this.value">
        @foreach (var ksiazka in Model)
            {
            <option VALUE="/Ksiazka/Ksiazka/@ksiazka.id">Książka nr @ksiazka.id</option>
        }
    </select>
    <br />

    <button onclick="location.href = '/Ksiazka/KsiazkaDoEdycji/0'">Nowa książka</button>                    
</body>
</html>