FakturaMvc/FakturaMvc/Models/Zajecia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FakturaMvc.Models
{
    public class Zajecia
    {
        public int id { get; set; } = 0;
        public string nazwa { get; set; } = string.Empty;
        public DateTime czasStartu { get; set; } = DateTime.MinValue;
        public string typ { get; set; } = string.Empty;
        public string miejsce { get; set; } = string.Empty;
        public DateTime czasKonca { get; set; } = DateTime.MinValue;
        public string prowadzacy { get; set; } = string.Empty;
        public double liczba1 { get; set; } = 0;
        public double liczba2 { get; set; } = 0;
        public string nazwaProjektu { get; set; } = string.Empty;
        public string pobierzOpis()
        {
            var opisZajecia = "Nazwa " + nazwa + ", czas startu " + czasStartu + ", typ " + typ + ", czas końca " + czasKonca
                + ", prowadzacy " + prowadzacy + ", trwanie " + czasTrwania() + ", wynik " + wynik() + ", nazwa projektu " + nazwaProjektu;
            if (czyWTrakcie() == true)

            {

                opisZajecia += ", w trakcie zajęć";
            }

            else

            {
                opisZajecia += ", poza zajęciami";
            }

            return opisZajecia;
        }
        public bool czyWTrakcie()
        {
            if (czasStartu.CompareTo(DateTime.Now) == -1)
            {
                if (czasKonca.CompareTo(DateTime.Now) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }

            else
            {
                return false;

            }
        }
        public string czasTrwania()
        {
            var godziny = (czasKonca - czasStartu).Hours;
            var minuty = (czasKonca - czasStartu).Minutes;
            var sekundy = (czasKonca - czasStartu).Seconds;
            var trwanie = godziny + ":" + minuty + ":" + sekundy;
            return trwanie;
        }

        public double wynik()

        {
            var wynik1 = liczba1 + liczba2;
            return wynik1;
        }
    }
}

FakturaMvc/FakturaMvc/Controllers/ZajeciaController.cs
using FakturaMvc.Mapper;
using FakturaMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FakturaMvc.Controllers
{
    public class ZajeciaController : Controller
    {
        // GET: Zajecia
        public ActionResult Zajecia(int id)
        {
            var zajeciaMapper = new ZajeciaMapper();
            var zajecia = zajeciaMapper.getById(id);
            return View(zajecia);
        }
        public ActionResult ListaZajec()
        {
            var zajeciaMapper = new ZajeciaMapper();
            var listaZajec = zajeciaMapper.getList();
            return View(listaZajec);
        }
        public ActionResult ZajeciaDoEdycji(int id)
        {
            Zajecia zajeciaDoEdycji;
            var zajeciaMapper = new ZajeciaMapper();
            if (id == 0)
            {
                zajeciaDoEdycji = new Zajecia();
                
            }
            else
            {
                zajeciaDoEdycji = zajeciaMapper.getById(id);
            }
            return View(zajeciaDoEdycji);
        }
        [HttpPost]
        public ActionResult ZajeciaDoEdycji(Zajecia zajeciaDoEdycji)
        {
            var zajeciaMapper = new ZajeciaMapper();
            zajeciaMapper.save(zajeciaDoEdycji);
            return Content($"Zajęcia numer {zajeciaDoEdycji.id} została zapisana poprawnie.");
        }
        public ActionResult UsunZajecia(int id)
        {
            Zajecia usunZajecia;
            var zajeciaMapper = new ZajeciaMapper();
            usunZajecia = zajeciaMapper.getById(id);
            var wynik = zajeciaMapper.delete(usunZajecia);
            if(wynik == true)
            {
                return Content($"Pomyślnie usunięto zajecia.");
            }
            else
            {
                return Content($"Problem z usunięciem zajecia.");
            }
        }
    }
}

FakturaMvc/FakturaMvc/Views/Zajecia/ListaZajec.cshtml
@model IEnumerable<FakturaMvc.Models.Zajecia>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ListaZajec</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
</head>
<body>
    <center><b>Lista Zajęć</b></center>
    <table style="width:100%; border: 1px solid black;">
        <tr>
            <th p align="left">ID</th>
            <th p align="left">Nazwa</th> 
            <th p align="left">typ</th>    
            <th p align="left">miejsce</th> 
            <th p align="left">prowadzacy</th>    
        </tr>
        @foreach (var zajecia in Model)
        {

            <tr>                
                <td><a href="/Zajecia/Zajecia/@zajecia.id ">@zajecia.id</a></td>            
                <td>@zajecia.nazwa</td>       
                <td>@zajecia.typ</td>    
                <td>@zajecia.miejsce</td>       
                <td>@zajecia.prowadzacy</td> 
                <td>
                    <button onclick="location.href = '/Zajecia/ZajeciaDoEdycji/@zajecia.id'">Edycja zajęcia @zajecia.id</button>

                </td>
                <td>
                    <button onclick="location.href = '/Zajecia/UsunZajecia/@zajecia.id'">Usuń zajęcia @zajecia.id</button>

                </td>   
            </tr>                       
        }

    </table>
    <select onchange="self.location.href = this.value">
        @foreach (var zajecia in Model)
            {
            <option VALUE="/Zajecia/Zajecia/@zajecia.id">Zajęcia nr @zajecia.id</option>
        }

    </select>
    <br />

    <button onclick="location.href = '/Zajecia/ZajeciaDoEdycji/0'">Nowa zajęcie</button>     
</body>
</html>

FakturaMvc/FakturaMvc/Views/Zajecia/Zajecia.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Zajecia</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
</head>
<body>
    <h1> Zajecia </h1>
    <table style="width:50%; border: 1px solid black;">
        <tr>
            <th p align="left">ID</p></th>
            <td>@Model.id</td>
        </tr>
        <tr>
            <th p align="left">Nazwa</p></th>
            <td>@Model.nazwa</td>
        </tr>
        <tr>
            <th p align="left">Typ</p></th>
            <td>@Model.typ</td>
        </tr>
        <tr>
            <th p align="left">Miejsce</p></th>
            <td>@Model.miejsce</td>
        </tr>
        <tr>
            <th p align="left">Prowadzący</p></th>
            <td>@Model.prowadzacy</td>
        </tr>
    </table>
</body>
</html>

FakturaMvc/FakturaMvc/Views/Zajecia/ZajeciaDoEdycji.cshtml
@model FakturaMvc.Models.Zajecia
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ZajeciaDoEdycji</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
</head>
<body>

    @using (Html.BeginForm("ZajeciaDoEdycji", "Zajecia", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <table style="width:50%; border: 1px solid black;">
            <tr>
                <th>@Html.LabelFor(a => a.id)</th>
                <td>@Html.TextBoxFor(a => a.id)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.nazwa)</th>
                <td>@Html.TextBoxFor(a => a.nazwa)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.typ)</th>
                <td>@Html.TextBoxFor(a => a.typ)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.miejsce)</th>
                <td>@Html.TextBoxFor(a => a.miejsce)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(a => a.prowadzacy)</th>
                <td>@Html.TextBoxFor(a => a.prowadzacy)</td>
            </tr>

        </table>
            <input type="submit" value="Zapisz" />

    }

</body>
</html>